FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends libpq-dev gcc && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p staticfiles media bundles

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "star_burger.wsgi:application"]