# Generated by Django 5.2.10 on 2026-01-18 14:50
from django.db import migrations
import phonenumbers
from phonenumber_field.phonenumber import PhoneNumber

def normalize_phonenumbers(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    for order in Order.objects.all():
        raw_number = str(order.phonenumber).strip()
        if not raw_number:
            continue
        try:
            parsed = phonenumbers.parse(raw_number, 'RU')
            if phonenumbers.is_valid_number(parsed):
                normalized = phonenumbers.format_number(
                    parsed, phonenumbers.PhoneNumberFormat.E164
                )
                order.phonenumber = normalized
                order.save(update_fields=['phonenumber'])
        except Exception:
            pass

def reverse_normalize_phonenumbers(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0038_order_orderitem'),
    ]

    operations = [
        migrations.RunPython(
            normalize_phonenumbers,
            reverse_code=reverse_normalize_phonenumbers
        ),
    ]
