# Generated by Django 5.2.10 on 2026-01-31 20:07

from django.db import migrations
from decimal import Decimal

def fix_orderitem_prices(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    Product = apps.get_model('foodcartapp', 'Product')
    
    product_prices = {
        product.id: product.price 
        for product in Product.objects.all()
    }
    
    updated_count = 0
    for item in OrderItem.objects.select_related('product').all():
        if item.product_id in product_prices:
            item.price = product_prices[item.product_id]
            item.save(update_fields=['price'])
            updated_count += 1
    
    print(f"Обновлено {updated_count} позиций заказов")

def reverse_fix_orderitem_prices(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_alter_order_options'),
    ]

    operations = [
        migrations.RunPython(fix_orderitem_prices, reverse_fix_orderitem_prices),
    ]
