# Generated by Django 5.2.10 on 2026-02-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20260131_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNPROCESED', 'Необработанный'), ('PROCESSING', 'Готовится'), ('DELIVERING', 'Доставляется'), ('COMPLETED', 'Выполнен')], db_index=True, default='UNPROCESSED', max_length=20, verbose_name='Статус'),
        ),
    ]
