# Generated by Django 5.2.10 on 2026-02-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNPROCESSED', 'Необработанный'), ('PROCESSING', 'Готовится'), ('DELIVERING', 'Доставляется'), ('COMPLETED', 'Выполнен')], db_index=True, default='UNPROCESSED', max_length=20, verbose_name='Статус'),
        ),
    ]
