# Generated by Django 5.2.10 on 2026-02-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_called_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'Электронно'), ('CASH', 'Наличностью')], db_index=True, default='ONLINE', max_length=10, verbose_name='Способ оплаты'),
        ),
    ]
