# Generated by Django 5.2.10 on 2026-02-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coords_error',
            field=models.BooleanField(default=False, help_text='Адрес не найден геокодером', verbose_name='Ошибка координат'),
        ),
        migrations.AlterField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата звонка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'Электронно'), ('CASH', 'Наличностью')], db_index=True, max_length=10, verbose_name='Способ оплаты'),
        ),
    ]
